In [3]:
a= input("enter a number")
print(a)

enter a number25
25


In [ ]:
A = 10
B = 20.5
C = "Hello"

print("value of A is",A,"type:",type(A))
print("value of B is",B,"type:",type(B))
print("value of C is",C,"type:",type(C))

value of A is 10 type: <class 'int'>
value of B is 20.5 type: <class 'float'>
value of C is Hello type: <class 'str'>


In [ ]:
#write a progam to perform arithmetic operation(+,-,/,*) by taking ipt form the user

flag=0
while(flag==0):
  a= int(input("number 1:"))
  b= int(input("number 2:"))

  print("Enter operator(+,-,*,/)")
  operator=input('operator:')


  if operator=='+':
     print(a+b)
  elif operator=='-':
     print(a-b)
  elif operator=='*':
     print(a*b)
  elif operator=='/':
     print(a/b)
  else:
     print("Wrong Input")

  check=input("Do you want to continue(y/n):")
  if(check=='n'):
    flag=1 #change the flag status
    print("Exit")
  elif(check=='y'):
    flag=0
    print("Program Continue...")


number 1:5
number 2:7
Enter operator(+,-,*,/)
operator:+
12
Do you want to continue(y/n):n
Exit


In [ ]:
def input_op():
  A = int(input("number 1:"))
  B = int(input("number 2:"))

  flag=0
  while(flag==0):
    print("Enter operator(+,-,*,/)")
    op=input('operator:')
    if (op=='*' or op=='/' or op=='+' or op=='-'):
      flag=1
      print("right operator selected")
    else:
      flag=0
      print("Wrong Input")
  return([A,B,op])

In [ ]:
def execution_func(input_list):
  a=input_list[0]
  b=input_list[1]
  op=input_list[2]
  if(op=="+"):
    c=a+b
    print("Result:",c)
  elif(op=="-"):
    c=a-b
    print("Result:",c)
  elif(op=="*"):
    c=a*b
    print("Result:",c)
  elif(op=="/"):
    c=a/b
  print("Result:",c)
  return([c,op])

In [ ]:
def check_execution():
  f2=0
  while(f2==0):
    chk = input("Do you want to continue(y or n):")
    if(chk=="n" or chk=="N"):
      flag=1
      f2=1
      print("Program exited")
    elif(chk=="y" or chk=="Y"):
      flag=0
      f2=1
      print("Program continued")
    else:
      print("Wrong selected")
      f2=1
  return(flag)

In [ ]:
#main program
flag=0
while(flag==0):

  input_lst=input_op() #call the input function to take the inputs and operation

  execution_func(input_lst) #call the execution function to perform operation

  flag=check_execution() #chaeck for the continuation

number 1:3
number 2:9
Enter operator(+,-,*,/)
operator:-
right operator selected
Result: -6
Result: -6
Do you want to continue(y or n):n
Program exited


In [ ]:
#command to install numpy library
!pip install numpy


In [ ]:
import numpy as np

# create a numpy array
V = np.array([20,30,40,5])
D = [20,30,40,50]
print(V, type(V))
print(D, type(D))

[20 30 40  5] <class 'numpy.ndarray'>
[20, 30, 40, 50] <class 'list'>


In [ ]:
# convert the list D into the numpy array
var = np.array(D)
print(var)
print(type(var))

[20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
var2 = var.copy() # copy the content of the var into var2

print(var)
print(var2)
print("\n")
R = var+var2
Y = var-var2
Z = var*var2
T = var/var2

print(R)
print(Y)
print(Z)
print(T)

[20 30 40 50]
[20 30 40 50]


[ 40  60  80 100]
[0 0 0 0]
[ 400  900 1600 2500]
[1. 1. 1. 1.]


In [ ]:
# few functions
val = np.arange(19) #(start(0),stop(N),step(1))
print(val)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [ ]:
# few functions
val = np.arange(1,10,0.5) # (start(0),stop(N),step(1))
print(val)
print("total number of elements ",val.size)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
total number of elements  18


In [ ]:
# linspace
val2 = np.linspace(1,2,200) # (start,stop,num_of_samples)
print('samples number:',val2.size)
print(val2)

samples number: 200
[1.         1.00502513 1.01005025 1.01507538 1.0201005  1.02512563
 1.03015075 1.03517588 1.04020101 1.04522613 1.05025126 1.05527638
 1.06030151 1.06532663 1.07035176 1.07537688 1.08040201 1.08542714
 1.09045226 1.09547739 1.10050251 1.10552764 1.11055276 1.11557789
 1.12060302 1.12562814 1.13065327 1.13567839 1.14070352 1.14572864
 1.15075377 1.15577889 1.16080402 1.16582915 1.17085427 1.1758794
 1.18090452 1.18592965 1.19095477 1.1959799  1.20100503 1.20603015
 1.21105528 1.2160804  1.22110553 1.22613065 1.23115578 1.2361809
 1.24120603 1.24623116 1.25125628 1.25628141 1.26130653 1.26633166
 1.27135678 1.27638191 1.28140704 1.28643216 1.29145729 1.29648241
 1.30150754 1.30653266 1.31155779 1.31658291 1.32160804 1.32663317
 1.33165829 1.33668342 1.34170854 1.34673367 1.35175879 1.35678392
 1.36180905 1.36683417 1.3718593  1.37688442 1.38190955 1.38693467
 1.3919598  1.39698492 1.40201005 1.40703518 1.4120603  1.41708543
 1.42211055 1.42713568 1.4321608  1.43718593

In [ ]:
# random value generation
# this function will generate thev random numbers within 0-1 range
np.random.seed(50) # this is the random state variable which should be any postive integer
val3 = np.random.random((10))
print(val3)

[0.49460165 0.2280831  0.25547392 0.39632991 0.3773151  0.99657423
 0.4081972  0.77189399 0.76053669 0.31000935]


In [ ]:
# generate the random numbers in between 10-50
a = 10
b = 50

val4 = a+(b-a)*np.random.random((20))
print(val4)

[46.47558534 21.81919233 46.88698761 14.57586285 39.53845663 33.74758321
 38.03525432 30.29131451 32.07698333 45.17105407 12.44272085 27.5563422
 37.88900378 38.80407432 32.05466776 26.44360541 42.87184149 45.61801122
 22.13585239 26.98090157]
